name: Run Job Checker

on:
  schedule:
    - cron: "0 13 * * *"  # 8:00 AM CDT
    - cron: "0 17 * * *"  # 12:00 PM CDT
    - cron: "0 22 * * *"  # 5:00 PM CDT
    - cron: "0 1 * * *"   # 8:00 PM CDT (technically next day UTC)
  workflow_dispatch:       # allows manual run from the GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - name: Commit updated seen_jobs.txt
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add seen_jobs.txt
        git commit -m "Update seen_jobs.txt [bot]" || echo "No changes to commit"
        git push
